# Generated by Django 5.1.7 on 2025-03-08 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('stake_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('debate_ongoing', 'Debate Ongoing'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('staker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('is_hallucination', models.BooleanField()),
                ('stake_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('challenged', 'Challenged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('ai_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.airesponse')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger_stake_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_pot', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='core.airesponse')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_debates', to=settings.AUTH_USER_MODEL)),
                ('challenged_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='core.review')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
