# Generated by Django 5.1.7 on 2025-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='staker',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='model',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
