# Generated by Django 5.1.7 on 2025-03-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_airesponse_staker_airesponse_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='on_hold',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
