# Generated by Django 5.1.7 on 2025-03-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallet_on_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reviewing', 'Reviewing'), ('challenged', 'Challenged'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
