# Generated by Django 5.1.7 on 2025-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='challenger_stake_amount',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='total_pot',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stake_amount',
        ),
        migrations.AddField(
            model_name='debate',
            name='challenger_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debate',
            name='is_hallucination',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debate',
            name='justification',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debate',
            name='reviewer_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='confirmed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('challenged', 'Challenged'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
