# Generated by Django 5.1.7 on 2025-03-08 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_debate_challenger_stake_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='confirmed_count',
        ),
        migrations.AddField(
            model_name='review',
            name='confirmed_by',
            field=models.ManyToManyField(related_name='confirmed_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('debate_ongoing', 'Debate Ongoing'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='debate',
            name='is_hallucination',
            field=models.BooleanField(default=False),
        ),
    ]
