# Generated by Django 5.1.7 on 2025-03-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_review_confirmed_count_review_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='correction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
