# Generated by Django 5.1.7 on 2025-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='correction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
