# Generated by Django 5.1.7 on 2025-03-08 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_debate_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='challenger_vote',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='reviewer_vote',
        ),
        migrations.AddField(
            model_name='debate',
            name='challenger_vote',
            field=models.ManyToManyField(related_name='challenger_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debate',
            name='reviewer_vote',
            field=models.ManyToManyField(related_name='reviewer_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
